### PR TITLE
changed footer style

### PR DESCRIPTION
**Pull request by tahseenzahra**

### CODE REVIEW

**Comment by tahseenzahra** [comment]
SharedScreenshot
screenshot of changes I have made

**Comment by Samarth-Sinha-V-2** [comment]
Its not looking good can you just mention all of them in one line

All the social media and the email icon ?

**Comment by tahseenzahra** [comment]
and still, if you want to change that I can go for that

**Comment by sinhasamarth** [comment]
Hey @tahseenzahra can you please remove the icons on bottom  footer and other things are amazing

**Comment by tahseenzahra** [comment]
I just want to clear something for myself before I start are you talking about the second picture and you want icons to be below contacts

**Comment by sinhasamarth** [comment]
image
Hey Check out this @tahseenzahra  and thanks for your time and efforts

**Comment by tahseenzahra** [comment]
it's my pleasure to work on your repo.
Here I am attaching a few screenshots please tell me which one you want... 
SharedScreenshot1
SharedScreenshot
here u can see that email icon that was already there because of that the gap between two icons is more as compared to others, therefore, I used another icon. And one more thing should I add social links that you have provided in readme.md.

**Comment by Samarth-Sinha-V-2** [comment]
Feel free to use another icon thanks

**Comment by tahseenzahra** [comment]
okey

**Comment by tahseenzahra** [comment]
I am done. Check now

**Comment by sinhasamarth** [comment]
hey @tahseenzahra it's not responsive can you fix it 
image

**Pull request merged**
